### ISSUE TITLE
why remove this epic feature

### ISSUE THREAD

**Issue by Coderx-Gamer** [krispyking24/ui-utils#1]

**Comment by MrBreakNFix** [comment]
Yeah, its in there for a reason!

**Comment by krispyking24** [comment]
late ik but to answer the question because i didn't want or need it so i done what i did. 
edit:seams like coderx even completely removed it then selfs as seen by this commit
https://github.com/Coderx-Gamer/ui-utils/commit/509f281a1890a0ef1e3cb66e0451721350b346fb
